spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.101.189.10:3306/springcloud_sell?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: 47.101.189.10
    port: 5672
    username: guest
    password: guest
  redis:
    host: 47.101.189.10
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env:
  dev3
girl:
  name: liuyifei
  age: 35
